---
- hosts: winhost
  gather_facts: true

#  vars:
#  - jump2_source: /home/ALM/archive.zip
#  - jump2_dest: \\192.168.56.120\destination

  tasks:
#  - name: Jump2 - Fetch files from AT to Win
#    fetch:
#      src: "{{ jump2_source }}"
#      dest: "{{ jump2_dest }}"
#      remote_src: yes
#      flat: yes
#      validate_checksum: no

  - name: Jump2 - win_copy files from AT to Win
    win_copy:
      src: /trans/archive.zip
      dest: C:\ALM\destination\
