---
- name: Create Cron jobs for WAS Housekeeping
  hosts: node1
  gather_facts: yes
  become: yes
  become_user: root

  tasks:
    - name: Create Individual Cron Job
      ansible.builtin.cron:
        name: "Zip up txt files in /tmp"
        minute: "58"
        hour: "*"
        day: "*"
        job: find /tmp -type f -name "*.txt" -mmin +120 -exec /bin/gzip -f -9 {} \;
