---
- hosts: node1
  gather_facts: false
  become: yes
  become_user: root

  vars_prompt:
  - name: in_path
    prompt: Where are the files?  i.e. /home/toweradmin/logs
    private: no

  - name: in_pattern
    prompt: Whats their pattern?  i.e. message*.log.gz
    private: no

  - name: in_age
    prompt: What is the age of the files you want to archive?  i.e. 30s (30 seconds), 5m (5 minutes), 6h (6 hours), 1d (1 days), or 3w (3 weeks)
    private: no

  tasks:
  - name: Ansible find files matching {{in_pattern}} in {{in_path}} aged {{in_age}}
    find:
      paths: "{{in_path}}"
      patterns: "{{in_pattern}}"
      age: "{{in_age}}"
      recurse: yes
    register: files_matched

  - name: Print the files that matched {{in_pattern}} in {{in_path}} and are over {{in_age}} old
    debug:
      msg: "{{ item.path }}"
    with_items: '{{ files_matched.files }}'

  - name: Delete archive files from var {{ files_matched.files}}
    file:
      path: "{{ item.path }}"
      state: absent
    with_items: "{{ files_matched.files }}"
